/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ConcurrentERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ConcurrentERC20__factory>
getContractFactory(name: 'ParallelLike', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ParallelLike__factory>

  getContractAt(name: 'ConcurrentERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ConcurrentERC20>
getContractAt(name: 'ParallelLike', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ParallelLike>

  deployContract(name: 'ConcurrentERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConcurrentERC20>
deployContract(name: 'ParallelLike', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ParallelLike>

  deployContract(name: 'ConcurrentERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConcurrentERC20>
deployContract(name: 'ParallelLike', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ParallelLike>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  