/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConcurrentERC721 } from './ConcurrentERC721.js';
export type { IERC721Receiver } from './IERC721Receiver.js';